name: Projek WS Continuous Integarion

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    build:
        name: Build and Test
        environment: development
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up NodeJS v.18
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - name: Setup MySQL
              uses: mirromutth/mysql-action@v1.1
              with:
                  mysql user: ${{ secrets.DB_USER }}
                  mysql password: ${{ secrets.DB_PASSWORD }}
                  mysql database: ${{ vars.DB_NAME }}

            - name: Install dependencies
              run: npm install && npm ci

            - name: Setup Prisma
              run: npx prisma generate

            - name: Run tests
              run: npm test
              env:
                  DB_HOST: ${{ vars.DB_HOST }}
                  DB_PORT: ${{ vars.DB_PORT }}
                  DB_NAME: ${{ vars.DB_NAME }}
                  DB_USER: ${{ secrets.DB_USER }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
